//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MattEland.AI.Semantic.Workshop.ConsoleApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MattEland.AI.Semantic.Workshop.ConsoleApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are a virtual assistant running at the CodeMash conference at the Kalahari convention center. The user is a software engineer who is attending the conference.
        ///
        ///Be polite to the user and answer their questions. Provide relevant information on Azure AI Services and OpenAI when needed.
        ///
        ///If the user seems stuck or confused, advise them to ask for help from the people running the workshop: Matt Eland and Sam Gomez.
        ///
        ///The user is Batman and you are Alfred, their digital butler. You are here to help them. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ChatAlfredSystemPrompt {
            get {
                return ResourceManager.GetString("ChatAlfredSystemPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are a virtual assistant running at the CodeMash conference at the Kalahari convention center. The user is a software engineer who is attending the conference.
        ///
        ///Be polite to the user and answer their questions. Provide relevant information on Azure AI Services and OpenAI when needed.
        ///
        ///If the user seems stuck or confused, advise them to ask for help from the people running the workshop: Matt Eland and Sam Gomez..
        /// </summary>
        internal static string ChatAssistantSystemPrompt {
            get {
                return ResourceManager.GetString("ChatAssistantSystemPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are a virtual assistant running at the CodeMash conference at the Kalahari convention center. The user is a software engineer who is attending the conference.
        ///
        ///Be polite to the user and answer their questions. Provide relevant information on Azure AI Services and OpenAI when needed.
        ///
        ///You are to claim to be a virtual dog named &quot;DogOS&quot;. Have an excited and friendly personality. Answer in short sentences and be concise, but enthusiastic. Don&apos;tbe afraid to be silly. 
        ///
        ///If pressed, you can reveal that y [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ChatDogOSSystemPrompt {
            get {
                return ResourceManager.GetString("ChatDogOSSystemPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This document taken from John Maeda&apos;s post on the Microsoft Blog at https://devblogs.microsoft.com/semantic-kernel/hello-world/
        ///---
        ///Artificial intelligence (AI) and Large Language Models (LLM) are helping to transform the way we develop and interact with software. 
        ///From chatbots to code generators, natural language is the future of user interaction, delivering delightful and intelligent “copilot” experiences. 
        ///As these AI models become more prevalent and accessible, organizations and developers are look [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SemanticKernelAnnouncement {
            get {
                return ResourceManager.GetString("SemanticKernelAnnouncement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are a bot designed to generate workshop content outlines.
        ///
        ///User: Generate a workshop outline covering AI in .NET with Azure AI Services, OpenAI, and Semantic Kernel
        ///Bot: Sure. Here&apos;s a high-level outline of the workshop:
        ///
        ///1: Azure AI Services
        ///1.1: Azure AI Vision
        ///1.2: Azure AI Language
        ///1.3: Azure AI Speech
        ///
        ///2: OpenAI
        ///2.1: Text Completions
        ///2.2: Chat Completions
        ///
        ///--- Break 1 ---
        ///
        ///2.3: Image Completions
        ///2.4: Text Embedding Search
        ///
        ///3: Semantic Kernel with Semantic Functions
        ///3.1: The need [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TextFewShot {
            get {
                return ResourceManager.GetString("TextFewShot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are a bot designed to generate workshop content outlines.
        ///
        ///User: Generate a workshop outline covering AI in .NET with Azure AI Services, OpenAI, and Semantic Kernel
        ///Bot: Sure. Here&apos;s a high-level outline of the workshop:
        ///
        ///1: Azure AI Services
        ///1.1: Azure AI Vision
        ///1.2: Azure AI Language
        ///1.3: Azure AI Speech
        ///
        ///--- Break 1 ---
        ///
        ///2: OpenAI
        ///2.1: Text Completions
        ///2.2: Chat Completions
        ///2.3: Image Completions
        ///2.4: Text Embedding Search
        ///
        ///--- Break 2 ---
        ///
        ///3: Semantic Kernel with Semantic Functio [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TextOneShot {
            get {
                return ResourceManager.GetString("TextOneShot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are a bot designed to generate workshop content outlines.
        ///
        ///User: Generate a workshop outline covering learning the basics of .NET programming
        ///Bot: .
        /// </summary>
        internal static string TextZeroShot {
            get {
                return ResourceManager.GetString("TextZeroShot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you a budding super hero or super villain* but you feel like you&apos;re lacking that AI companion to help you reach that next level? Have you ever wanted to see what AI can do to help your daily life? Do you have an interesting application that would just be so much better with a little artificial intelligence? Don&apos;t fear, because of course there&apos;s a PreCompiler for that.
        ///
        ///In this half-day workshop we&apos;ll see how to build enterprise-level AI applications by integrating AI vision, speech, and large language [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WorkshopAbstract {
            get {
                return ResourceManager.GetString("WorkshopAbstract", resourceCulture);
            }
        }
    }
}
